enum Roles {
  ADMIN
  USER
}

type Family {
  name: String!
  ages: [Int]!
  user: User!
}

type Me {
  id: ID!
  email: String
  username: [String]!
  fullName: String!
  result: Float
  phone: [Int]!
  apiKey: String!
  users: [User]!
  verified: Boolean!
  role: Roles!
}

type User {
  email: String!
  username: String!
  fullName: String!
  phone: String!
  family: Family!
}

input UserInfoInput {
  id: ID!
  name: String!
}

type UserInput {
  name: String!
  email: String!
}

type Query {
  getMe: Me
  getUserByUsername(username: String!, id: Int!): User
  isAdmin(username: String!): Boolean!
  getUser(where: UserInfoInput!): User
}

type Mutation {
  createUser(input: UserInput!): User!
}